[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Redirecionamento de API v1 (proxy) para as funções Netlify
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirecionamento de fallback para a SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/v1/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"