[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/mp/*"
  to = "/.netlify/functions/express-api/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "axios", "uuid", "@supabase/supabase-js", "cors", "crypto"]
  included_files = ["netlify/functions/certs/**"]
  # Explicitly define the express-api function
  # This is usually not needed if functions are in the functions directory
  # but can help with dependency issues.
  # express-api = { directory = "netlify/functions/express-api" }