[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Regra específica para as rotas do Mercado Pago via servidor Express
[[redirects]]
  from = "/api/mp/*"
  to = "/.netlify/functions/express-api/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Regra "Catch-all" para SPAs (Single Page Applications)
# Redireciona todas as outras rotas para o index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200